### ISSUE TITLE
clojure-lsp support

### ISSUE THREAD

**Issue by ericdallo** [aidalgol/dockered-language-servers#2]
Hi, I'm the clojure-lsp maintainer and I'm interested in adding support for clojure-lsp in this project, WDYT?

https://clojure-lsp.github.io/clojure-lsp/

**Comment by aidalgol** [comment]
Hi, thanks for your interest!  I've just pushed a change that adds a "Contributing" section to the README, which I think is everything you need to know.  Let me know if you still have questions.

**Comment by aidalgol** [comment]
Update: I have split that section out into a separate `CONTRIBUTING` file.

**Comment by ericdallo** [comment]
@aidalgol maybe you should mention the new file on README?
